# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LIN-Akimon' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LIN-Akimon
  pod 'AFNetworking', '~> 3.0'
  pod 'KVNProgress'
  pod 'SDAutoLayout', '~> 2.1.6'
  pod 'SDWebImage'
  pod 'SDCycleScrollView', '~> 1.64'
  pod 'MJExtension','~> 3.0.10'
  

  target 'LIN-AkimonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LIN-AkimonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
